version: "3"

services:
  api:
    container_name: "zakaz"
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    container_name: "database"
    image: postgres:16
    restart: always
    env_file: .env
    ports:
      - "5432:5432"

  frontend-nginx:
    container_name: "frontend-nginx"
    env_file: .env
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - VITE_AP_URL=${VITE_API_URL}
    ports:
      - 80:80
