version: "3"

services:
  backend:
    container_name: "backend"
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - "3000:3000"
    networks:
      - net
    depends_on:
      - postgres
    volumes:
      - ./backend/public/uploads:/app/public/uploads

  postgres:
    container_name: "database"
    image: postgres:16
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net

  frontend:
    container_name: "frontend"
    env_file: .env
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - net
    depends_on:
      - backend
    volumes:
      - ./ssl:/etc/ssl

networks:
  net:
    driver: bridge

volumes:
  postgres_data:
