version: "3"

services:
  api:
    container_name: "zakaz"
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - 4000:3000
    depends_on:
      - postgres

  postgres:
    container_name: "database"
    image: postgres:16
    restart: always
    env_file: .env

  frontend:
    container_name: "frontend-nginx"
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 81:80
